### ISSUE TITLE
CH03 not working

### ISSUE THREAD

**Issue by NickNYU** [zxh0/jvmgo-book#15]
亲爱的作者，我是您书的忠实粉丝，哈哈
最近刚刚完成第三章，发现总是解析 Constant Pool的tag时候出错，fmt出来发现有3位数的tag出现
然后就到您这边下载了原书code，编译以后发现load class时候出现同样的问题
```
$ ./ch03.exe -cp "C:\Develop\Java\JVM" test
Constant Pool Length: 43panic: 215

goroutine 1 [running]:
panic(0x53f9e0, 0xc08241a390)
        C:/Go/src/runtime/panic.go:481 +0x3f4
main.loadClass(0xc08200a256, 0x4, 0xc0820522a0, 0x1)
        C:/Develop/GO/src/jvmgo-source/ch03/main.go:36 +0x105
main.startJVM(0xc0820122d0)
        C:/Develop/GO/src/jvmgo-source/ch03/main.go:23 +0xfc
main.main()
        C:/Develop/GO/src/jvmgo-source/ch03/main.go:16 +0x124

```

不知可否答疑解惑

多谢哈

**Comment by NickNYU** [comment]
您的code没问题，我编译的时候路径指定的是您的folder，但是编译出来还是用的我原来的文件
我自己去找原因啦，打扰了

**Comment by zxh0** [comment]
问题解决就好 ：）
